[tool.poetry]
name = "flojoy-cloud"
version = "0.2.2"
description = ""
authors = ["Joey Yu <joey@flojoy.io>", "Jeff Zhang <jeff@flojoy.io>"]
readme = "README.md"
packages = [{ include = "flojoy_cloud" }]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.26.0"
numpy = "^1.26.3"
pydantic = "^2.5.3"
pandas = "^2.2.0"
watchfiles = "^0.21.0"
rich = "^13.7.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
ipykernel = "^6.29.0"
python-dotenv = "^1.0.1"
plotly = "^5.18.0"
nbformat = "^5.9.2"
ruff = "^0.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
